### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by endergrimm** [OFFTKP/pokemon-bot#9]
I have tried to compile this a couple times and have not had luck. I get a few errors about variables not being initialized? Would it be possible to get more detailed build instructions or a docker container for this?  I have noticed I have to install gcc for this to work and also clone the protocol folder separately.

**Comment by endergrimm** [comment]
To add some more context this is the error I am seeing during attempted compilation: 
# bot/DiscordBot
./bot.go:149:4: undefined: hold
./bot.go:213:13: undefined: gifWidth
./bot.go:214:13: undefined: gifHeight
./bot.go:230:5: undefined: profiling
./bot.go:231:43: undefined: timeStart
./bot.go:482:2: ex declared but not used
./bot.go:498:10: undefined: get
./command_status.go:17:10: undefined: get
./main.go:114:32: cannot use gamePath (variable of type string) as type int in struct literal
./main.go:114:54: cannot use timeout (variable of type int) as type string in struct literal
./main.go:114:54: too many errors

**Comment by OFFTKP** [comment]
Hello, DiscordBot was in the process of a complete rewrite (which is as of now unfinished and will be unfinished for a while)

Can you use this older commit here and tell me if you have issues?: https://github.com/OFFTKP/discord-plays/tree/c1439282741fe812b09df951bebc8934343c3a8b ?

**Comment by endergrimm** [comment]
Thanks I was able to get that to compile and run! I had some weird issues mostly related to me using docker and not running it as interactive at first to generate the config. Thanks for all the help!

**Comment by OFFTKP** [comment]
Great!
